apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: file:////Users/aweeu/Desktop/mlops_cicd/mlflow+minio+postgres
    targetRevision: HEAD
    path: minio
  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true