apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-auth-config
  namespace: test
data:
  basic_auth.ini: |
    [mlflow]
    database_uri = postgresql://postgres:postgres@postgres:5432/posgtres
    default_permission = NO_PERMISSIONS
    admin_username = admin
    admin_password = password
