apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: your-node-name
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        ports:
        - containerPort: 5432
