apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: test
spec:
  selector:
    app: minio
  type: NodePort # ОБЯЗАТЕЛЬНО указать чтобы не было проблем с прокси
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 32090