apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: test
  labels:
    type: vol1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/minio

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: vol1
  resources:
    requests:
      storage: 10Gi
